title: "Statistical Computing and Introduction to Data Science"
description: "GR5206/4206 - Fall 2025"
baseurl: "/stat_computing_python"
url: "https://cueods.github.io/stat_computing_python/"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# Navigation
header_pages:
  - courses/stat_computing/lectures/learning_python_intro.html
  - teaching-team.md
  - instructor-bio.md
  - academic-honesty.md
  - setup/conda_and_navigator_setup.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
