title: "Statistical Computing"
description: "GR5206/4206 - Fall 2025"
baseurl: "/stat_computing_python"
url: "https://mingzhoujin.github.io"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# Navigation
header_pages:
  - homework/index.md
  - academic-honesty.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
